module.exports = {
  USERS: "users",
  USER: {
    ADD_USER: "ADD_USER",
    ADD_CURRENT_USER: "ADD_CURRENT_USER",
    USER_SIGNOUT: "USER_SIGNOUT",
    SIGNOUT: "SIGNOUT",
    UPDATE_USER: "UPDATE_USER",
    WATCH_USER: "WATCH_USER",
    UPDATE_REQUEST: "UPDATE_REQUEST",
    UPDATE_FRIEND: "UPDATE_FRIEND",
    UPDATE_GROUP: "UPDATE_GROUP",
    UPDATE_CHAT: "UPDATE_CHAT",
    WATCH_REQUESTS: "WATCH_REQUESTS",
    WATCH_FRIENDS: "WATCH_FRIENDS",
    WATCH_GROUPS: "WATCH_GROUPS",
    WATCH_CHATS: "WATCH_CHATS",
    STOP_USER_SYNC: "STOP_USER_SYNC",
    STOP_REQUESTS_SYNC: "STOP_REQUESTS_SYNC",
    STOP_FRIENDS_SYNC: "STOP_FRIEND_SYNC",
    STOP_GROUPS_SYNC: "STOP_GROUPS_SYNC",
    STOP_CHATS_SYNC: "STOP_CHATS_SYNC",
    STOP_GROUPS_CHATS_SYNC: "STOP_GROUPS_CHATS_SYNC",
    UPDATE_STATUS: "UPDATE_STATUS",
    UPDATE_GROUPS: "UPDATE_GROUPS",
    SELECT_CHAT: "SELECT_CHAT",
    ACCEPT_REQUEST: "ACCEPT_REQUEST",
    DECLINE_REQUEST: "DECLINE_REQUEST",
    UPDATE_REQUESTS: "UPDATE_REQUESTS"
  },
  CHATS: {
    SEND_CHAT_REQUEST: "SEND_CHAT_REQUEST",
    SEND_CHAT: "SEND_CHAT",
    UPDATE_CHATS: "UPDATE_CHATS",
    READ_REQUEST: "READ_REQUEST"
  },
  PAGE: {
    UPDATE_LOADING: "UPDATE_LOADING",
    UPDATE_TITLE: "UPDATE_TITLE"
  }
};
